### ISSUE TITLE
 ID_conversion ?

### ISSUE THREAD

**Issue by kobolock** [ThomasBeder/ALLCatchR#6]
Hi,

Thank you very much for this tool.
I have just a question about your R code in the script [ALLCatcheR.R](https://github.com/ThomasBeder/ALLCatchR/blob/main/R/ALLCatcheR.R). What represents exactly the object "ID_conversion" ? If I try to follow the code step by step, this object is not found.
Best,
Samuel

**Comment by kobolock** [comment]
Found in sysdata.rda

**Comment by jotech** [comment]
hi, the object contains gene ids for matching and should be loaded automatically. Did you install and load the package when you tried this?
