### ISSUE TITLE
not able to run ALLCatchR

### ISSUE THREAD

**Issue by mariasolruiz** [ThomasBeder/ALLCatchR#9]
Hello, 
I am trying to run the software using my RNA-seq results. The test included in the package runs ok. 
In my sample, I have the counts in tpm, and I'm doing a test with only two samples. The input file looks like this:

"target_id"	"sample_HLP011"	"sample_HLP009"
"ENST00000415118.1"	0	0
"ENST00000434970.2"	0	0
"ENST00000448914.1"	0	0
"ENST00000632684.1"	0	0
"ENST00000631435.1"	0	0

But using the following code , I get an error:

allcatch(Counts.file = "combined_counts.txt", ID_class = "ensemble_ID", sep = "\t")

counts loaded...
Error in apply(Counts.norm, 2, scale) : 
  dim(X) must have a positive length

I would appreciate any suggestions, 

Thank you, 

Maria Sol

**Comment by ThomasBeder** [comment]
Hello Maria Sol,
the problem is the ".1"/".2" in the Ensembl IDs. ALLCatchR needs them without the extension.

Best
Thomas

**Comment by mariasolruiz** [comment]
Hello Thomas, 
thank you for your reply. I removed the version number from the Ensembl IDs, but I still get the same error. The input looks like this>

value           sample_HLP011 sample_HLP009
   <chr>                   <dbl>         <dbl>
 1 ENST00000542354          1.53         0.737
 2 ENST00000390423          1.48         1.42 
 3 ENST00000390436          2.93         0.843
 4 ENST00000390441          1.01         0.731
 5 ENST00000390341          1.73         3.51 

Thank you,

Sol

**Comment by ThomasBeder** [comment]
Hello Sol,
the reason is that you provide Enseml transcript IDs, not gene IDs. They start with ENSG. I did not recognize this in your first message. Sorry for that. Do you have the original raw counts for the data? ALLCatchR was not thoroughly tested on tpms.

**Comment by mariasolruiz** [comment]
Thank you, I was able to run it now!
